language: python
python:
  - "2.7"
#  - "pypy"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - cd lib/sophia
  - git checkout v1.2.2
  - make
  - cd ../../
# command to run tests ...
script:
  - cd sppy_unit_test/dict/
  - python single_db_u32_run.py


